id: I70F7713C
ocr_import_info:
  bdrc_scan_id: W1KG16455
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-03-08 19:51:38.625207
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16455
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG16455
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འགྲེལ་པ་དོན་གསལ་དང་། རྣམ་བཤད་སྙིང་པོ་རྒྱན་གྱི་དགོངས་འགྲེལ་ཚིག་དོན་རབ་གསལ།
  languages:
  - bo
  author: སེངྒེ་བཟང་པོ།
bases:
  I1KG16457:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16457
      total_pages: 444
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG16457.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
